name: file_open_example
description: Example for file_open plugin.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  file_open:
    path: ../

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  msix: ^3.16.12

msix_config:
  display_name: file_open example
  publisher_display_name: file open example
  identity_name: fileopenexample.FileOpenExample
  msix_version: 1.0.0.0
  capabilities: internetClient, location, microphone, webcam, privateNetworkClientServer, internetClientServer
  publisher: CN=file open example
  certificate_subject: CN=file open example
  store: false
  file_extension: ".abcde"
